import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="border-b">
          <div className="max-w-5xl mx-auto p-4 flex gap-4">
            <a href="/" className="font-medium">Study+Stay</a>
            <a href="/intake" className="text-sm">Intake</a>
            <a href="/profile" className="text-sm">Profile</a>
            <a href="/accommodation" className="text-sm">Housing</a>
            <a href="/swipe" className="text-sm">Programs</a>
            <a href="/visa" className="text-sm">Visa</a>
            <a href="/cv" className="text-sm">CV</a>
            <a href="/chat" className="text-sm">Chat</a>
          </div>
        </nav>
        <main className="max-w-5xl mx-auto p-4">{children}</main>
      </body>
    </html>
  );
}
